import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { ScrollArea } from "@/components/ui/scroll-area";
import { ArrowLeft } from "lucide-react";

const PAGES = {
  terms: {
    title: "Terms of Service",
    version: "v1.0 — Effective March 6, 2026",
    content: `
## 1. Acceptance of Terms
By accessing or using the Nexus Platform ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Service.

## 2. Beta Disclaimer
Nexus is currently in BETA. The platform is provided "as-is" without warranty of any kind. Features may change, be removed, or experience downtime. Data may be reset during the beta period.

## 3. Account Registration
You must provide accurate information when creating an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities under your account.

## 4. BYOK (Bring Your Own Key) Model
Nexus operates on a BYOK model where you provide your own API keys for third-party AI providers. You are responsible for compliance with each provider's terms of service. Nexus encrypts and stores your keys securely but is not liable for charges incurred through your API keys.

## 5. AI-Generated Content
All content generated by AI agents on the platform is provided for informational purposes only. AI outputs may contain errors, inaccuracies, or biased information. You are solely responsible for reviewing, validating, and determining the suitability of AI-generated content before use.

## 6. Code Execution
The code execution sandbox is provided for development purposes. You must not use it to execute malicious code, perform unauthorized access, or violate any laws. Nexus is not liable for the output of code executed in the sandbox.

## 7. Intellectual Property
- Content you create on Nexus (messages, documents, code, wiki pages) remains your intellectual property.
- AI-generated content ownership is subject to the respective AI provider's terms.
- Nexus retains no ownership rights over your content.

## 8. Acceptable Use
You agree not to: use the platform for illegal activities, attempt to reverse-engineer the platform, use AI agents to generate harmful content, abuse API rate limits, or share your account credentials.

## 9. Data Handling
Your data is stored in MongoDB Atlas with encryption. API keys are encrypted using Fernet encryption. See our Privacy Policy for full details on data collection and handling.

## 10. Provider Pass-Through Terms
When using third-party AI providers through Nexus, their respective terms apply to the AI-generated outputs. Nexus acts as an orchestration layer and is not responsible for provider-side data handling.

## 11. Limitation of Liability
To the maximum extent permitted by law, Nexus shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the Service.

## 12. Termination
We may terminate or suspend your account at any time for violation of these Terms. You may delete your account at any time through Settings.

## 13. Changes to Terms
We may update these Terms at any time. Continued use of the Service after changes constitutes acceptance of the new Terms. You will be notified of material changes and required to re-accept.

## 14. Contact
For questions about these Terms, contact support through the platform's built-in support desk.
    `,
  },
  privacy: {
    title: "Privacy Policy",
    version: "v1.0 — Effective March 6, 2026",
    content: `
## 1. Information We Collect

**Account Information:** Name, email address, profile picture (from OAuth providers).

**API Keys:** Third-party AI provider API keys, encrypted with Fernet encryption and stored in MongoDB Atlas.

**Chat & Content Data:** Messages, documents, wiki pages, code repository files, project tasks, and knowledge base entries you create.

**Usage Data:** AI collaboration counts, workflow executions, feature usage metrics.

**Authentication Data:** Session tokens (HTTPOnly cookies), OAuth tokens from Google/Microsoft/Meta.

**Audit Logs:** Actions taken on the platform for security and compliance purposes.

## 2. How We Use Your Data
- To provide and operate the Nexus platform
- To authenticate your identity
- To pass your API keys to third-party AI providers when you initiate AI collaboration
- To store and display your content (messages, files, wiki pages, tasks)
- To generate analytics and usage reports
- To improve the platform

## 3. Third-Party AI Providers
When you use AI agents, your conversation data is sent to the respective AI provider (Anthropic, OpenAI, Google, etc.) according to your API key configuration. Each provider's privacy policy governs their handling of your data. We recommend reviewing each provider's data policy.

## 4. Data Storage & Security
- **Database:** MongoDB Atlas with TLS encryption in transit
- **API Keys:** Encrypted using Fernet symmetric encryption
- **Sessions:** HTTPOnly cookies with SameSite=None, Secure=True
- **Per-Tenant Encryption:** Optional dedicated encryption keys per organization

## 5. Data Retention
- Account data is retained while your account is active
- Deleted accounts enter a 30-day grace period before permanent deletion
- Chat messages are retained per workspace settings
- Audit logs are retained for 12 months

## 6. Your Rights (GDPR)
- **Access:** View your data through your account
- **Portability:** Export all your data via Settings > Profile > Export My Data
- **Erasure:** Delete your account via Settings > Profile > Delete My Account
- **Rectification:** Update your profile information at any time

## 7. Cookies
We use essential HTTPOnly cookies for authentication. See our cookie consent banner for details on optional cookies.

## 8. Children's Privacy
Nexus is not intended for users under 16 years of age.

## 9. Changes to This Policy
We will notify you of material changes to this Privacy Policy and update the effective date.

## 10. Contact
For privacy inquiries, contact support through the platform.
    `,
  },
  "acceptable-use": {
    title: "Acceptable Use Policy",
    version: "v1.0 — Effective March 6, 2026",
    content: `
## 1. Purpose
This Acceptable Use Policy ("AUP") defines prohibited activities on the Nexus Platform.

## 2. Prohibited Activities

### Content Generation
- Do not use AI agents to generate content that is illegal, defamatory, or infringes on intellectual property rights
- Do not generate deepfake content intended to deceive or harm
- Do not create content that promotes violence, hate speech, or discrimination

### Platform Abuse
- Do not attempt prompt injection attacks against AI agents
- Do not use the code execution sandbox for unauthorized access, cryptocurrency mining, or denial-of-service attacks
- Do not abuse automation features (workflows, auto-collaboration) to spam or overwhelm systems
- Do not share account credentials or access another user's account

### AI Agent Misuse
- Do not use AI agents to generate malware, exploits, or attack tools
- Do not use agents to circumvent content filters of underlying AI providers
- Do not create agents with system prompts designed to produce harmful outputs

### Data & Privacy
- Do not use the platform to collect or process personal data without consent
- Do not upload copyrighted content without permission
- Do not use voice cloning features without explicit consent from the voice owner

## 3. Rate Limits & Fair Use
- AI collaboration rounds are limited per workspace configuration (5-50 rounds)
- Per-agent rate limits are enforced to prevent API provider lockout
- Excessive API calls may result in temporary throttling

## 4. Enforcement
Violation of this AUP may result in:
- Warning notification
- Temporary feature restriction
- Account suspension
- Permanent account termination

## 5. DMCA Takedown
If you believe content on Nexus infringes your copyright, submit a takedown request through our support desk. We will respond within 72 hours.

## 6. Reporting
Report AUP violations via the platform's content flagging feature or through the support desk.
    `,
  },
};

export default function LegalPage() {
  const navigate = useNavigate();
  const path = window.location.pathname.replace("/", "");
  const page = PAGES[path] || PAGES.terms;

  useEffect(() => { window.scrollTo(0, 0); }, [path]);

  return (
    <div className="min-h-screen bg-zinc-950 text-zinc-300">
      <div className="max-w-3xl mx-auto px-6 py-8">
        <button onClick={() => navigate(-1)} className="flex items-center gap-1 text-sm text-zinc-500 hover:text-zinc-300 mb-6">
          <ArrowLeft className="w-4 h-4" /> Back
        </button>
        <h1 className="text-2xl font-bold text-zinc-100 mb-1" style={{ fontFamily: "Syne, sans-serif" }}>{page.title}</h1>
        <p className="text-xs text-zinc-600 mb-8">{page.version}</p>
        <div className="prose prose-invert prose-sm max-w-none">
          {page.content.split("\n").map((line, i) => {
            const lineKey = `legal-${i}-${line.slice(0, 20).replace(/\W/g, '')}`;
            if (line.startsWith("## ")) return <h2 key={lineKey} className="text-lg font-semibold text-zinc-100 mt-6 mb-2">{line.replace("## ", "")}</h2>;
            if (line.startsWith("### ")) return <h3 key={lineKey} className="text-base font-medium text-zinc-200 mt-4 mb-1">{line.replace("### ", "")}</h3>;
            if (line.startsWith("**") && line.endsWith("**")) return <p key={lineKey} className="font-semibold text-zinc-200 mt-2">{line.replace(/\*\*/g, "")}</p>;
            if (line.startsWith("- ")) return <li key={lineKey} className="ml-4 text-sm text-zinc-400">{line.replace("- ", "")}</li>;
            if (line.trim() === "") return <br key={lineKey} />;
            return <p key={lineKey} className="text-sm text-zinc-400 leading-relaxed">{line}</p>;
          })}
        </div>
        <div className="mt-12 pt-6 border-t border-zinc-800 text-xs text-zinc-600">
          <p>Nexus Platform Beta &copy; {new Date().getFullYear()}. All legal documents should be reviewed by a qualified attorney.</p>
        </div>
      </div>
    </div>
  );
}
